### ISSUE TITLE
Initial changes

### ISSUE THREAD

**Issue by lilahmedina** [lilahmedina/quote-machine#1]
Some features could work better and be more modern. I will work on this sometime in the future. 

### Task for the future

- [x] fix color change for every quote change. 
- [x] Clean up code to improve readability.  
- [x] update the Twitter icon to X. 
- [x] update the favicon.
- [x] optimize button margins. 

website: https://lilah-randomquotes.netlify.app/
[![Netlify Status](https://api.netlify.com/api/v1/badges/9e4219a4-e632-4265-a63a-e2530d499457/deploy-status)](https://app.netlify.com/sites/lilah-randomquotes/deploys)

> The most common way people give up their power is by thinking they don’t have any.  _- Alice Walker_

**Comment by lilahmedina** [comment]
~~update the Twitter icon to X.~~
just removed the twitter button entirely.
